# Generated by Django 2.2.14 on 2020-12-17 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_auto_20201215_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lista',
            name='posicion',
            field=models.IntegerField(unique=True),
        ),
    ]
