# Generated by Django 2.2.14 on 2020-12-17 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0004_auto_20201216_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
