# Generated by Django 2.2.14 on 2020-12-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='visibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
