# Generated by Django 2.2.14 on 2020-12-15 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(null=True)),
                ('posicion', models.IntegerField(default=models.AutoField(primary_key=True, serialize=False, unique=True))),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.Lista')),
                ('miembros', models.ManyToManyField(related_name='tarjetas', to='usuarios.Usuario')),
            ],
        ),
    ]
